title: Remer's Devlog
description: Flexton is a responsive and ultra-minimal theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://remerer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Hongpyo Jang
author-image:   1.jpg
author-job:     Back-end Developer / Game Client Developer
author-email:   remerer@gmail.com # Add your email for contant form.
author-twitter:  # Add your twitter account
about-author:   I am a web developer focusing on front-end development. Always hungry to keep learning.

# Social settings
social-twitter:   
social-facebook:
social-github:    remerer
social-pinterest: 
social-instagram: 
social-youtube:
social-vk:   
social-linkedin: Hongpyo Jang

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
